### PR TITLE
Added draft theme for the Los Angeles Times

### PR DESCRIPTION
**Pull request by palewire**
screenshot from 2019-02-10 11-38-12

### CODE REVIEW

**Comment by domoritz** [comment]
@palewire This is fantastic. Thank you! I look forward to reviewing it once the tests pass. You should be able to run `yarn run fix` to fix linting issues.

**Comment by palewire** [comment]
When I run yarn lint it's throwing an error but not giving me any traceback.

```bash
$ yarn lint
yarn run v1.13.0
$ tslint -p . && prettier --list-different '{src,test}/**/*.ts'
src/theme-latimes.ts
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's what happens if I run your command.

```bash
$ yarn run fix
yarn run v1.13.0
error Command "fix" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any tips?

**Comment by domoritz** [comment]
> When I run yarn lint it's throwing an error but not giving me any traceback.

I just fixed that in master. Prettier recently added support for `--check`.

**Comment by domoritz** [comment]
Sorry, the command is `yarn format`

**Comment by palewire** [comment]
Done.

**Comment by domoritz** [comment]
:tada

**Pull request merged**
