### PR TITLE
Five thirty eight v 1.1

### PR DESCRIPTION
**Pull request by Casyfill**
Tweaked in response to #6 

- grid for X and Y
- tick labels are grey
- tick label font size is now 10, not 12
- axis titles, legends, title are dark-dark-grey, but not black
- symbols are filled

### CODE REVIEW

**Comment by Casyfill** [comment]
screen shot 2018-10-08 at 11 13 03 am

**Comment by Casyfill** [comment]
@domoritz sorry to bother, but what does that error mean? I think I reformatted everything, and can build js from that file

**Comment by domoritz** [comment]
It doesn't show an error on travis but `src/theme-fivethirtyeight.ts` is not formatted correctly. You can use prettier to format it and then Travis will pass.

**Comment by Casyfill** [comment]
Yay! Should be GTG now!

**Comment by domoritz** [comment]
Hmm, should axis labels have that low contrast?

**Comment by domoritz** [comment]
@Casyfill Can you update the Pr so that we can merge it?

**Comment by domoritz** [comment]
Please send a new pr.

**Pull request closed without merging**
