### PR TITLE
Save state

### PR DESCRIPTION
**Pull request by iFlameing**
Fixes #24

### CODE REVIEW

**Comment by iFlameing** [comment]
@domoritz You can merge this. I tested locally and it works fine :)

**Comment by iFlameing** [comment]
@domoritz I pushed a new commit with adding graph in url.

**Comment by domoritz** [comment]
@iFlameing Can you help finish this?

**Comment by iFlameing** [comment]
@domoritz I already rename the themes into theme and renderer in https://github.com/vega/vega-themes/pull/26/commits/ad86522b2ce1f62dcb98d860cceacd7f2727c08c

**Pull request merged**
